### ISSUE TITLE
Module does not install completely

### ISSUE THREAD

**Issue by pluex1** [matrix-org/synapse-user-restrictions#5]
**Describe the bug**
when you try to install the module, only the dist-info directory is created, but not the plugin itself.

**To Reproduce**
1. clone the repo into a path of your choice
2. pip install path/to/synapse-user-restrictions
3. no errors

**Expected behavior**
I expect the module somewhere under /usr/lib/.
But under the path there is only the *dist-info directory.

**Additional context**
Tested in docker and on Ubuntu 20.04.

**Comment by babolivier** [comment]
Thanks for reporting @pluex1! I've opened https://github.com/matrix-org/synapse-user-restrictions/pull/6 to fix this.
